name: Build and test
ru-name: Build and test workflow
on: 
 push: 
 pull_request:
  types: 
    - opened
    - edited
jobs:
  builds:
   runs-on: ubuntu-latest
   steps: 
    - uses: actions/checkout@v3
      name: Checkout project
    - uses: actions/setup-java@v3
      name: Setup java
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle 
      uses: gradle/gradle-build-action@v2 
    - name: Run build with Gradle Wrapper 
      run: ./gradlew build
